name: DES2020
channels:
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pandas
  - openpyxl
  - matplotlib
  - plotly  
  - jupyter_client
  - ipywidgets
  - networkx
  - tqdm
  - sphinx
  - pip:
    - simpy
    - sphinx-autobuild
    - sphinx_rtd_theme
